Import("env")

import os
import re
from pathlib import Path
from typing import List

project_dir = Path(env.subst("$PROJECT_DIR"))
default_secret_dir = Path.home() / ".aac-secrets" / "aac"


def _c_string(v: str) -> str:
    if v is None:
        v = ""
    # Normalize line endings and keep PEM newlines as escaped \n in C literal.
    v = v.replace("\r\n", "\n").replace("\r", "\n")
    v = v.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{v}"'


def _env_str(name: str, default: str = "") -> str:
    return os.environ.get(name, default).strip()


def _config_header_define(name: str, default: str = "") -> str:
    cfg = project_dir / "include" / "config.h"
    if not cfg.exists():
        return default
    try:
        text = cfg.read_text(encoding="utf-8")
    except Exception:
        return default
    m = re.search(
        rf'^\s*#\s*define\s+{re.escape(name)}\s+"([^"]+)"\s*$',
        text,
        flags=re.MULTILINE,
    )
    if not m:
        return default
    return (m.group(1) or "").strip() or default


def _env_int(name: str, default: int) -> int:
    raw = _env_str(name, "")
    if not raw:
        return default
    try:
        return int(raw, 10)
    except ValueError:
        print(f"[secrets] invalid int for {name}='{raw}', using {default}")
        return default


def _secret_dir() -> Path:
    raw = _env_str("AAC_SECRET_DIR", str(default_secret_dir))
    p = Path(raw).expanduser()
    if not p.is_absolute():
        p = (project_dir / p).resolve()
    return p


out_dir = project_dir / ".pio" / "secrets"
out_dir.mkdir(parents=True, exist_ok=True)
out_file = out_dir / "generated_secrets.h"


def _read_text_if_exists(path_like: str) -> str:
    p = Path(path_like)
    if not p.is_absolute():
        p = project_dir / p
    if not p.exists() or not p.is_file():
        return ""
    return p.read_text(encoding="utf-8").strip()


def _is_valid_pem_blob(value: str) -> bool:
    s = (value or "").strip()
    return bool(s) and "-----BEGIN " in s and "-----END " in s


def _env_pem(name: str, placeholder: str, fallback_paths: List[str]) -> str:
    raw = _env_str(name, "")
    if raw and raw != placeholder:
        # Allow either raw PEM content or a file path in env.
        from_file = _read_text_if_exists(raw)
        candidate = from_file if from_file else raw
        if _is_valid_pem_blob(candidate):
          return candidate
    for rel in fallback_paths:
        v = _read_text_if_exists(rel)
        if _is_valid_pem_blob(v):
            return v
    return placeholder


def _pem_key_kind(pem: str) -> str:
    s = (pem or "").strip()
    if not s:
        return "missing"
    if "BEGIN RSA PRIVATE KEY" in s:
        return "rsa"
    if "BEGIN EC PRIVATE KEY" in s:
        return "ec"
    if "BEGIN PRIVATE KEY" in s:
        return "pkcs8"
    return "unknown"

waqi = _env_str("WAQI_API_TOKEN", "")
aws_endpoint = _env_str(
    "AWS_IOT_ENDPOINT",
    _config_header_define("AWS_IOT_ENDPOINT", "YOUR_AWS_IOT_ENDPOINT"),
)
aws_port = _env_int("AWS_IOT_PORT", 8883)
aws_root_ca = _env_pem(
    "AWS_IOT_ROOT_CA_PEM",
    "YOUR_AWS_IOT_ROOT_CA_PEM",
    [
        str(_secret_dir() / "AmazonRootCA1.pem"),
        "certs/AmazonRootCA1.pem",
        "data/AmazonRootCA1.pem",
    ],
)
aws_dev_cert = _env_pem(
    "AWS_IOT_DEVICE_CERT_PEM",
    "YOUR_AWS_IOT_DEVICE_CERT_PEM",
    [
        str(_secret_dir() / "device_cert.pem"),
        str(_secret_dir() / "device-cert.pem"),
        "certs/device_cert.pem",
        "data/device_cert.pem",
        "certs/device-cert.pem",
        "data/device-cert.pem",
    ],
)
aws_dev_key = _env_pem(
    "AWS_IOT_PRIVATE_KEY_PEM",
    "YOUR_AWS_IOT_PRIVATE_KEY_PEM",
    [
        str(_secret_dir() / "device_private.key"),
        str(_secret_dir() / "device-private.key"),
        str(_secret_dir() / "private.key"),
        "certs/device_private.key",
        "data/device_private.key",
        "certs/device-private.key",
        "data/device-private.key",
        "certs/private.key",
        "data/private.key",
    ],
)
aws_claim_cert = _env_pem(
    "AWS_IOT_CLAIM_CERT_PEM",
    "YOUR_AWS_IOT_CLAIM_CERT_PEM",
    [
        str(_secret_dir() / "claim_cert.pem"),
        str(_secret_dir() / "claim-cert.pem"),
        "certs/claim_cert.pem",
        "data/claim_cert.pem",
        "certs/claim-cert.pem",
        "data/claim-cert.pem",
    ],
)
aws_claim_key = _env_pem(
    "AWS_IOT_CLAIM_PRIVATE_KEY_PEM",
    "YOUR_AWS_IOT_CLAIM_PRIVATE_KEY_PEM",
    [
        str(_secret_dir() / "claim_private.key"),
        str(_secret_dir() / "claim-private.key"),
        "certs/claim_private.key",
        "data/claim_private.key",
        "certs/claim-private.key",
        "data/claim-private.key",
    ],
)

header = f"""// Auto-generated by scripts/pio/generate_secrets_header.py
// Do not edit manually. File location: .pio/secrets/generated_secrets.h
#pragma once

#ifndef WAQI_API_TOKEN
#define WAQI_API_TOKEN {_c_string(waqi)}
#endif

#ifndef AWS_IOT_ENDPOINT
#define AWS_IOT_ENDPOINT {_c_string(aws_endpoint)}
#endif

#ifndef AWS_IOT_PORT
#define AWS_IOT_PORT {aws_port}
#endif

#ifndef AWS_IOT_ROOT_CA_PEM
#define AWS_IOT_ROOT_CA_PEM {_c_string(aws_root_ca)}
#endif

#ifndef AWS_IOT_DEVICE_CERT_PEM
#define AWS_IOT_DEVICE_CERT_PEM {_c_string(aws_dev_cert)}
#endif

#ifndef AWS_IOT_PRIVATE_KEY_PEM
#define AWS_IOT_PRIVATE_KEY_PEM {_c_string(aws_dev_key)}
#endif

#ifndef AWS_IOT_CLAIM_CERT_PEM
#define AWS_IOT_CLAIM_CERT_PEM {_c_string(aws_claim_cert)}
#endif

#ifndef AWS_IOT_CLAIM_PRIVATE_KEY_PEM
#define AWS_IOT_CLAIM_PRIVATE_KEY_PEM {_c_string(aws_claim_key)}
#endif
"""

out_file.write_text(header, encoding="utf-8")

# Inject generated header into compile units.
env.Append(CPPPATH=[str(out_dir)])
env.Append(CCFLAGS=["-include", str(out_file)])
env.Append(CXXFLAGS=["-include", str(out_file)])

loaded = {
    "WAQI_API_TOKEN": bool(waqi),
    "AWS_IOT_ENDPOINT": bool(aws_endpoint and aws_endpoint != "YOUR_AWS_IOT_ENDPOINT"),
    "AWS_IOT_ROOT_CA_PEM": bool(aws_root_ca and aws_root_ca != "YOUR_AWS_IOT_ROOT_CA_PEM"),
    "AWS_IOT_DEVICE_CERT_PEM": bool(
        aws_dev_cert and aws_dev_cert != "YOUR_AWS_IOT_DEVICE_CERT_PEM"
    ),
    "AWS_IOT_PRIVATE_KEY_PEM": bool(
        aws_dev_key and aws_dev_key != "YOUR_AWS_IOT_PRIVATE_KEY_PEM"
    ),
    "AWS_IOT_CLAIM_CERT_PEM": bool(
        aws_claim_cert and aws_claim_cert != "YOUR_AWS_IOT_CLAIM_CERT_PEM"
    ),
    "AWS_IOT_CLAIM_PRIVATE_KEY_PEM": bool(
        aws_claim_key and aws_claim_key != "YOUR_AWS_IOT_CLAIM_PRIVATE_KEY_PEM"
    ),
}
print(
    "[secrets] generated header: "
    + str(out_file)
    + " | loaded="
    + ", ".join(f"{k}:{'yes' if v else 'no'}" for k, v in loaded.items())
)

device_key_kind = _pem_key_kind(aws_dev_key)
claim_key_kind = _pem_key_kind(aws_claim_key)
print(
    f"[secrets] key types: device={device_key_kind} claim={claim_key_kind}"
)
if device_key_kind == "rsa":
    print(
        "[secrets][warn] AWS_IOT_PRIVATE_KEY_PEM is RSA. "
        "ESP32 MQTT/TLS may fail with RSA memory pressure; prefer EC/P-256."
    )
if claim_key_kind == "rsa":
    print(
        "[secrets][warn] AWS_IOT_CLAIM_PRIVATE_KEY_PEM is RSA. "
        "Fleet provisioning on ESP32 is more reliable with EC/P-256."
    )
