#!/usr/bin/env bash
set -euo pipefail

STACK_NAME="${1:-AacCloud-next}"
OUT_FILE="${2:-scripts/aws/smoke.env}"

get_out() {
  local key="$1"
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --query "Stacks[0].Outputs[?OutputKey=='${key}'].OutputValue" \
    --output text
}

API_BASE_URL="$(get_out HttpApiUrl)"
COGNITO_USER_POOL_ID="$(get_out CognitoUserPoolId)"
COGNITO_CLIENT_ID="$(get_out CognitoClientId)"
COGNITO_ISSUER="$(get_out CognitoIssuer)"
COGNITO_HOSTED_DOMAIN_URL="$(get_out CognitoHostedDomainUrl)"

cat > "$OUT_FILE" <<ENVFILE
# Generated by scripts/aws/init-smoke-env.sh from stack: $STACK_NAME
# Fill ACCESS_TOKEN and DEVICE_ID before running smoke.

API_BASE_URL="$API_BASE_URL"
ACCESS_TOKEN=""
DEVICE_ID=""
CLAIM_SECRET=""
SMOKE_STRICT_DESIRED="0"

# Helpful references for login/token flow:
COGNITO_USER_POOL_ID="$COGNITO_USER_POOL_ID"
COGNITO_CLIENT_ID="$COGNITO_CLIENT_ID"
COGNITO_ISSUER="$COGNITO_ISSUER"
COGNITO_HOSTED_DOMAIN="$COGNITO_HOSTED_DOMAIN_URL"
ENVFILE

echo "Wrote $OUT_FILE"
echo "Next: set ACCESS_TOKEN and DEVICE_ID, then run: ./scripts/aws/run-cloud-smoke.sh"
